[build]
  base = "."
  command = "cp dist/index.html || mkdir -p dist && cp dist/index.html"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200